### PR TITLE
Make preconditions more readable

### PR DESCRIPTION
**Pull request by michaelbaudino**
This PR provides no feature at all :trollface: 

It's just trying to make preconditions code more readable by:
* using more guard clause
* renaming a few things
* moving long string messages to constants (I first tried with custom error classes but it actually made the code longer)
* use `system()` return value rather than backticks + `$?.exitstatus` combination
* refactoring input/output

I'm still unhappy with the class hierarchy / singleton trick, but I can't figure out an elegant way of doing it yet 😕

### CODE REVIEW

**Comment by EugenMayer** [comment]
Thank you a lot for the work. I will look into this on the weekend and merge it by the mid/end of the next week, when 0.4.x has been stabilised.

**Comment by EugenMayer** [comment]
@michaelbaudino its really about time to invite you as a contributor. Really great work already, thank you for fixing my language also.. i am annoying, i imagine that.

Great contributions.

Rules are actually easy: big stuff -> pull request, small fixes -> right into the master.
And if you do something, a issue would be perfect to have for it.

Or in other words - just do what you did before :) Thank you!

**Comment by michaelbaudino** [comment]
I'm quite honored 😊

**Comment by EugenMayer** [comment]
@michaelbaudino if you wonder why i still did not merge this - it has the potentials to break things -and i have literally broken enough with 0.4.x which i try to hotfix right now. When it is done, thats the first one to merge

**Comment by michaelbaudino** [comment]
Yeah, that was my guess, but don't worry: I'm just maintaining it up-to-date and fixing a few mistakes I'm encountering 👍 

I'm waiting for it to start working on `--[-no]-auto-install` and `--[-no]auto-upgrade` more comfortably, but I'm still pretty sure we can find a better class hierarchy / organization 🤔

**Comment by michaelbaudino** [comment]
Closing this for now, since I have another branch with a different refactoring approach, actually closer to what we discussed in #377

**Comment by EugenMayer** [comment]
Sure, as you wish, tensed to see what you will come up with!

**Pull request closed without merging**
