### PR TITLE
[BUGFIX] Relative path should be from config file

### PR DESCRIPTION
**Pull request by mickaelperrin**
Relative path sets in the config file seems to be resolved from where the docker-sync process start not from the config file.

This PR forces the relative pathsof `src` to be computed from the path of the `docker-sync.yml` file.

### CODE REVIEW

**Comment by mickaelperrin** [comment]
Mmm, wait it seems there is a problem with that

**Comment by mickaelperrin** [comment]
Seems better now

**Comment by EugenMayer** [comment]
makes a lot of sense when using the config path when resolving relative paths, but as far as i understand, absolute paths would be broken now?

**Comment by mickaelperrin** [comment]
Good question, I didn't check indeed. Personally, I avoid absolute paths for portability issues. But I agree both should work.

**Comment by mickaelperrin** [comment]
I think [expand_path](http://ruby-doc.org/core-1.9.3/File.html#method-c-expand_path) works like [absolute_path](http://ruby-doc.org/core-1.9.3/File.html#method-c-absolute_path), if the main path is absolute it will remain as is.
Did a quick test, and seems to work accordingly.

**Comment by EugenMayer** [comment]
Well when you have a normalized development installation and your run several projects, i can become handy to start / stop something from the other projects, that were "absolute" paths like '~/Development/projects/X' shine.

Thank for testing this!

**Pull request merged**
