### PR TITLE
Allow alternative implementations of unison-fsmonitor

### LINKED ISSUE #775: Allow alternative implementations of unison-fsmonitor
### Error/Feature Requestion/Docs
There's an [alternative implementation of unison-fsmonitor](https://github.com/autozimu/unison-fsmonitor) which uses Facebook `watchman` and it's insanely faster compared to [eugenmayer/dockersync/unox](https://github.com/hnsl/unox) (we're talking <1s vs 2-5s for each update). Unfortunately to use it I had to modify the code of `docker-sync` to prevent it from forcing me to remove it and installing `unox` instead.

It would be amazing if we could somehow disable the `unox` check, either with --flag or even ENV var.

### PR DESCRIPTION
**Pull request by d4rky-pl**
Fixes #775

### CODE REVIEW

**Comment by d4rky-pl** [comment]
@EugenMayer Hey, is there anything else you need to make this one land? I'm also happy to provide alternative implementation if you don't like this one, just let me know!

**Review by EugenMayer — APPROVED** [review]
I like the idea! Thank you for the contribution

**Comment by d4rky-pl** [comment]
@EugenMayer hey, I pushed the update of the docs I proposed in #775, is there anything else I can add or improve to make this land? I would like to start onboarding my team members to use this so we can tell if there are any caveats or issues that I missed (I've been using this for the past 4 days with zero problems so far)

**Review by EugenMayer — APPROVED** [review]
i like that!

**Comment by EugenMayer** [comment]
If you are good to go, i would merge that one in, let you run a bit and then plan a release with it. Thanks for putting your effort into it!

**Comment by d4rky-pl** [comment]
@EugenMayer I'm totally good to go, if we discover any issues I'll let you know 👍

**Comment by EugenMayer** [comment]
Thank you a lot for the contribution @d4rky-pl !

**Comment by AlexandruGG** [comment]
hey @EugenMayer @d4rky-pl, I've been following this. When is 0.7.0 due to be released? I can see the [milestone](https://github.com/EugenMayer/docker-sync/milestone/39) is complete and I'm keen to try it, looks great!

**Comment by EugenMayer** [comment]
@AlexandruGG i have no date yet. @d4rky-pl how is it working for you so far?

**Comment by d4rky-pl** [comment]
@EugenMayer I was on a vacation for a week but before that it worked without any issues, other than the aforementioned Unison one. If you modify files while it's currently syncing it'll miss the change until the next sync which is slightly easier to trigger now that syncing triggers almost instantaneously. None of the other people I've onboarded to this solution have complained so far either.

Considering that it's opt-in, I'd say release 0.7.0 and we can gather more feedback from a broader pool of different setups.

**Comment by EugenMayer** [comment]
AFAIU we have it pure opt in right now, right. So releasing 0.7.0 will not harm anybody using the old watcher.

**Comment by d4rky-pl** [comment]
@EugenMayer precisely 👍

**Comment by AlexandruGG** [comment]
@d4rky-pl @EugenMayer so can you release this please? 😅

**Comment by EugenMayer** [comment]
It's done, finally :)

**Pull request merged**
