### PR TITLE
Added support for --sync-prefix to add to sync_name

### PR DESCRIPTION
**Pull request by kducharm**
A solution to #439 which when a --sync-prefix is added, volumes specified in the docker-sync.yml will be prefixed with the specified value, feedback appreciated.

`docker-sync start --sync_prefix=myprefix_`

### CODE REVIEW

**Comment by EugenMayer** [comment]
Will not merge this if we do not write tests for this one - this has been tried by @mickaelperrin  back in the days and the outcome was, AFAIR, its not possible. 

@mickaelperrin can you remember any details?

**Comment by EugenMayer** [comment]
Any tests planned @kducharm ?

**Comment by kducharm** [comment]
@EugenMayer I've been a bit slammed but definitely would like to see this added. I'm currently using this on 4 projects on the same machine simultaneously and sync has been working great. I'll see what integration tests descriptions I can come up with, I'm not a ruby developer so I might need some help.

**Comment by kducharm** [comment]
@EugenMayer Rather than trying to introduce this parameter, I was able to create a docker-sync.template.yml file and prior to running docker-sync, used a custom build script to generate the right container name using token replacement into a docker-sync.yml prior to starting everything.

**Pull request closed without merging**
