### PR TITLE
Migrate to new unison images fixes #810

### LINKED ISSUE #810: Bug: Wrong Unison image is pulled on M1 Mac
### Error/Feature Requestion/Docs
When starting docker sync on an M1 Mac the wrong image is pulled. The AMD unison image is pulled by default regardless of architecture. Instead the ARM image should be pulled for ARM architecture machines.

### Docker Driver
Rancher Desktop with moby and dockerd

### Sync strategy
default (on osx)

### your docker-sync.yml
```
version: "2"
syncs:
  app-sync:
    src: './'
```

### OS
OSX Monterey 12.5.1

### Reference:
Original issue opened in unison repository https://github.com/EugenMayer/docker-image-unison/issues/28

### PR DESCRIPTION
**Pull request by EugenMayer**
Migrate to new unison images which are build for amd64/arm64 using manifests. This will fix #810 

- add ruby 3.0 to test matrix

### CODE REVIEW

**Comment by EugenMayer** [comment]
Since there are currently no CI engines available to run MacOS on M1, nor any MacOS offering CI that runs docker-for-mac (license issues), i cannot test docker-sync on it's home platform in the CI and thus rely on the community to do that testing - i do no longer own a mac

**Comment by yoseph1998** [comment]
@EugenMayer I see the gem version needs to be updated.

**Comment by EugenMayer** [comment]
@yoseph1998 you need to compile / run from source, yes

**Comment by yoseph1998** [comment]
@EugenMayer Yes, I have this branched cloned locally and I am running ./deploy_locally.sh

I updated the version locally to 0.7.3 so that I can validate the installed docker-sync is the one from this branch. 

I was only able to make this work with the changes proposed above (adding `ghcr.io/`)

**Comment by EugenMayer** [comment]
change the value in https://github.com/EugenMayer/docker-sync/blob/main/VERSION to 1.0.0 and run deploy locally again. be sure to run gem uninstall docker-sync before that

**Comment by EugenMayer** [comment]
Really odd i missed that after i actually already worked on those lines .. kind got lost over it.

Fixed it, could you try once again?

**Review by yoseph1998 — APPROVED** [review]
@EugenMayer Tested and working locally (M1 MacOS). Thank you!

**Comment by yoseph1998** [comment]
I don't see the version being updated in this MR, is that happening outside of the MR?

**Comment by EugenMayer** [comment]
Yes @yoseph1998  version will be planned when the release is planned. Which will happen very soon

**Comment by yoseph1998** [comment]
@EugenMayer Great. All LGTM. Again thank you for all this work!

**Comment by EugenMayer** [comment]
Your welcome, you did a fair share of this too. Thank you

**Review by yoseph1998 — APPROVED** [review]

**Pull request merged**
