### PR TITLE
Rsync single file

### PR DESCRIPTION
**Pull request by dojohnso**
Added some example settings for src/dest settings for full directory vs
a single file

### CODE REVIEW

**Comment by EugenMayer** [comment]
i the * mandatory to sync a folder ?

**Comment by dojohnso** [comment]
@EugenMayer yeah for whatever reason, when I don't use the "path/*" format, it creates a "path/path/" directory on the application image. i haven't dug into why too much. i just know that /* works. fswatch seems works fine with that as well.

**Comment by EugenMayer** [comment]
Well i recall that was the reason we auto added the slash.. hmm that will become an ugly upgrade bug

**Comment by dojohnso** [comment]
@EugenMayer when i just use "/this/path/", the fswatch output says:

> Synced /this/path
> Starting to watch /this/path- Press CTRL-C to stop

note it doesn't show the slash there. so it looks like something about the code needs the * to work as intended

**Comment by dojohnso** [comment]
@EugenMayer although I'm playing with some different configurations that might not require the *. I'll keep you posted.

**Comment by EugenMayer** [comment]
Thank you @dojohnso !

**Pull request merged**
