### PR TITLE
Refactor config loading process by turning config into a PORO instead of hash

### LINKED ISSUE #288: unison and unox are required even while using rsync
Hello, 
  I was trying to use rsync as sync_strategy, but it seems that the check for the `unison` and `unison-fsmonitor` it is hardcoded and does not respect the `sync_stragegy` configuration?

I got the first error:
> Could not find unison binary in path. Please install it, e.g. using "brew install unison"

...followed by:

> warning  Could not find unison-fsmonitor (for file watching) binary in $PATH. We try to install unox now (for manual instracutions see https://github.com/hnsl/unox.)
> Shall I install unison-fsmonitor for you? (y/N) n
>       error  Please install it, see https://github.com/hnsl/unox, or simply run :
>  curl "https://raw.githubusercontent.com/hnsl/unox/master/unox.py" -o "/usr/local/bin/unison-fsmonitor" && chmod +x /usr/local/bin/unison-fsmonitor

The only way to run docker-sync was to install both unison and unison-fsmonitor.
In my opinion if the `rsync` strategy is an accepted solution I don't see the reason why i would want to install unison if i'm not going to use it. :)

This is my `docker-sync.yml` file, if needed i can provide also `docker-compose(-dev).yml` files.

``` 
version: "2"
syncs:
  UNIQUENAME-htdocs-sync:
    src: './'
    dest: '/var/www/html'
    sync_host_ip: '127.0.0.1'
    sync_host_port: '10871'
    sync_userid: '82'
    sync_strategy: 'rsync'
    sync_excludes: ['docker-runtime/', ......]

```

### PR DESCRIPTION
**Pull request by ignatiusreza**
which would allow us to put more responsibility into the config itself, and turn it into a more reliable source of truth for deciding dependencies..

fix #288 & a prerequisite for #265

### CODE REVIEW

**Comment by ignatiusreza** [comment]
@EugenMayer I tried to focus solely on refactoring the configuration without touching too much into other stuff... and I also tried to not change the interface of `Docker_sync::SyncManager`, since that one seems to be designed to be extendable for custom scripting.. :crossed_fingers: that I didn't break anything..

hopefully this amount of changes are acceptable.. :grin:

**Comment by EugenMayer** [comment]
Great stuff, will have a look at it while i am traveling today. Thank you so much for so much work!

**Comment by EugenMayer** [comment]
Did some changes, will commit those in about 1 hour, there is quite a change though. Really nice work there and thank you for the test, great tooling and nice ruby skills over there!

**Comment by EugenMayer** [comment]
@ignatiusreza just see the commit messages, hopefully i did not cross your idea, i really like what you did there. Thanks

**Comment by ignatiusreza** [comment]
@EugenMayer nice ones! agreed that it looks better with locator & serializers being separated, and with configurable global config path, we can avoid stubbing in test :+1:

**Comment by EugenMayer** [comment]
Great contribution, thank you!

**Comment by esolitos** [comment]
Amazing contribution! Great job!

**Comment by ignatiusreza** [comment]
Awesomesauce!

**Pull request merged**
