### PR TITLE
Fix nil excludes error (rsync strategy)

### PR DESCRIPTION
**Pull request by yoseph1998**
Fix rsync nil error when sync_excludes is undefined.

### CODE REVIEW

**Comment by vokshirg** [comment]
not only one strategy affected https://github.com/EugenMayer/docker-sync/commit/190d93d44bde47d5c7d9f11e2ef329223bfd1364


unison also get: 
```
bad pattern:  .docker-sync/daemon.log
A pattern must be introduced by one of the following keywords:
Name, Path, BelowPath or Regex.
```

**Comment by EugenMayer** [comment]
@yoseph1998 is a dupe of #820

**Comment by EugenMayer** [comment]
Oh, one is for rsync, one is for unison .. and we will probably need one for native_osx too?

**Comment by EugenMayer** [comment]
Thank you for the contribution!

**Pull request merged**
