### PR TITLE
Be able to use environment variables in docker-sync.yml

### PR DESCRIPTION
**Pull request by vranac**
Added dotenv gem and setup the string interpolation with environment variables, this is supposed to solve the issue #212.

This is my first venture into ruby, and is kind of hack, so please forgive the possible messy code.

### CODE REVIEW

**Comment by EugenMayer** [comment]
Thank you for the contribution!

Could you put the variable replacement into a tool method to avoid the code duplication?
What would we need doc-wise, which dotenv file is used by default, since i do not see any specific file you load. Thanks

**Comment by vranac** [comment]
@EugenMayer https://github.com/bkeepers/dotenv by default load the .env file in the directory from where the command was called (and I think it traverses up as well), if there is no .env that is fine, if there is a env var replacement in docker-sync.yml an exception gets thrown.

I'll make the tool method commit in the next few hours

**Comment by EugenMayer** [comment]
Great, thanks. Do me a favour and write some basic docs on https://github.com/EugenMayer/docker-sync/wiki/Variable-Replace---Dynamic-Configuration - use to reference the official docs for sure, but describe how dotenv is utilized and give a short example. 

Please for https://github.com/EugenMayer/docker-sync-boilerplate and create a example project called dynamic-configuration-dotnev and use this how you intend it, link that in the docs.

In case of new features, we need to make clear how they work and how to utilize them. Thanks!

**Comment by vranac** [comment]
@EugenMayer sure, let me hammer out the ugly code first, as I mentioned I'm new to ruby, and am looking at option 2 approach form this answer http://stackoverflow.com/a/18965660/99219 for tool method, is this acceptable or is there a better way?

**Comment by EugenMayer** [comment]
Please create a file like this one, https://github.com/EugenMayer/docker-sync/blob/master/lib/docker-sync/preconditions.rb

Probably call it ConfigTemplate and implement the methods in there. Include that module if you need it like or define stack methods https://github.com/EugenMayer/docker-sync/blob/master/tasks/sync/sync.thor#L20

**Comment by vranac** [comment]
@EugenMayer thank you very much

**Comment by EugenMayer** [comment]
@vranac oh no sir, thanks all directed to you :)

**Comment by EugenMayer** [comment]
@vranac great stuff, thats great. Now just the docs and we are all set to merge!

**Comment by vranac** [comment]
@EugenMayer example added EugenMayer/docker-sync-boilerplate#4

**Comment by vranac** [comment]
@EugenMayer is there a way for me to fork a wiki and make a PR, or should I edit directly on this repo?

**Comment by EugenMayer** [comment]
wow this is all quick! thanks. Now just some little mentions here https://github.com/EugenMayer/docker-sync/wiki/Variable-Replace---Dynamic-Configuration and i go right way merge this little baby, very nice work!

Could You then please change your target branch to release/0.2.0 since this will be not part of the 0.1.6 release Thank you!

**Comment by EugenMayer** [comment]
@vranac dont fork the wiki, just be bold. No need to overcomplicate docs, or they will never happen - right :)

**Comment by vranac** [comment]
@EugenMayer oh this is happening, as it is critical for my teams setup :)

**Comment by vranac** [comment]
@EugenMayer https://github.com/EugenMayer/docker-sync/wiki/Variable-Replace---Dynamic-Configuration <- will this be satisfactory?

And when do you plan for 0.2.0 release?

**Comment by EugenMayer** [comment]
That is perfect. Well 0.2.0 is done, when its done, but check this https://github.com/EugenMayer/docker-sync/projects/1 

you can build this gem manually until its published and either publish it to your own gem server or use https://github.com/EugenMayer/docker-sync/blob/master/deploy_locally.sh on each machine until then - so you do not need to wait. Be sure to use the release/0.2.0 when you install

Could you please edit this PR and direct it to release/0.2.0? thanks!

Thanks for the great contribution!

**Comment by vranac** [comment]
@EugenMayer it is already pointing to `EugenMayer:release/0.2.0` or am I missing something?

**Comment by EugenMayer** [comment]
arg, sorry, it did not update for me. My bad!

**Comment by sloria** [comment]
Is there a way to disable automatic reading of `.env` files? I do more than just set envvars in my .env files, e.g. settings aliases and activating my Python virtual env because I used [autoenv](https://github.com/kennethreitz/autoenv).

Therefore, when docker-sync tries to read my `.env` file, it fails:

```
/usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:63:in `parse_line': Line "source activate osf" doesn't match format (Dotenv::FormatError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:47:in `block in call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:46:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:46:in `call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/parser.rb:36:in `call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/environment.rb:13:in `load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv/environment.rb:9:in `initialize'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:15:in `new'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:15:in `block (2 levels) in load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:59:in `ignoring_nonexistent_files'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:14:in `block in load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:46:in `block in with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:45:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:45:in `reduce'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:45:in `with'
        from /usr/local/lib/ruby/gems/2.4.0/gems/dotenv-2.2.0/lib/dotenv.rb:13:in `load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/lib/docker-sync/sync_manager.rb:19:in `initialize'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/tasks/sync/sync.thor:30:in `new'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/tasks/sync/sync.thor:30:in `start'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /usr/local/lib/ruby/gems/2.4.0/gems/docker-sync-0.2.0/bin/docker-sync:14:in `<top (required)>'
        from /usr/local/bin/docker-sync:22:in `load'
        from /usr/local/bin/docker-sync:22:in `<main>'
```

**Comment by sloria** [comment]
I reported my above issue in #254, so further discussion can happen there.

**Pull request merged**
