### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by michaelbaudino**
## Description

This PR introduces some integration testing that is able to start `docker-sync` (with a very basic config using `native_osx` strategy, for now) and check inside the sync container if `/host_sync` and `/app_sync` are synchronized with the host directory as expected.

It uses [rspec-bash](https://github.com/mdurban/rspec-bash) to run those integration tests in isolated and kinda stubbed environments.

## How to test

0. `git checkout add-integration-tests`
1. `bundle install`
2. `bundle exec rspec spec/integration`

ℹ️ A [manual debugging test](https://github.com/EugenMayer/docker-sync/blob/add-integration-tests/spec/integration/native-osx_strategy_spec.rb#L38-L45) can be anabled (by changing `xit` to `it`) to popup a Ruby console while `docker-sync` is started and running (enabling us to inspect the sync container in depth).

## ~~Current status~~

~~If I run the above commands on my computer, 3 tests fail: `/host_sync` is being correctly synchronized with the host dir, but not `/app_sync` 😱 Thanks to some [manual debugging](https://github.com/EugenMayer/docker-sync/blob/add-integration-tests/spec/integration/native-osx_strategy_spec.rb#L38-L45), I figured out that changes in host directory were properly applied to `/host_sync` directory inside the sync container, but they are not triggering any FS event (at least, no event is being recorded by `inotifywait -mr /host_sync`).~~

~~So I'm unsure if I found a way to reproduce #410 within those tests (even if I have no idea what's the reproducing factor) or if I just did something wrong in trying to reproduce a full-stack behaviour in a stubbed environment 🤔~~

~~Any help/feedback/result is welcome (cc @EugenMayer @ignatiusreza 💌 )~~

### CODE REVIEW

**Comment by EugenMayer** [comment]
Once again, such a great work. I will have to tackle this on the weekend due to my very hight work load right now - i will def. look into this and also check against the issue you found according the sync - very interesting indeed!

@michaelbaudino you are a hero !

**Comment by EugenMayer** [comment]
i get " The OS temporary directory (/var/folders/sf/b0tywk3s4g714kr0smymjdrw0000gn/T) does not seem to be shared with Hyperkit VM." eventhough /private is shared which does include `ls /private/var/folders/sf/b0tywk3s4g714kr0smymjdrw0000gn` - if if i try to add `/var/folders/sf` d4m tells me that this path is overlapping with /private

Not sure this is a false-positive, but in the end `F.*FFFFFF` nearly all tests fail

Iam on Sierra `10.12.5` with d4m `17.03.1-ce-mac12` running with ruby 2.2.4.

I am not sure which tests fail due to the reasons above, but at least this one cant really be related:

```
 1) native_osx strategy start creates a PID file
     Failure/Error: expect(File.file?('.docker-sync/daemon.pid')).to be true

       expected true
            got false
     # ./spec/integration/native-osx_strategy_spec.rb:28:in `block (3 levels) in <top (required)>'
     # ./spec/integration/native-osx_strategy_spec.rb:22:in `block (4 levels) in <top (required)>'
     # ./spec/integration/native-osx_strategy_spec.rb:18:in `block (3 levels) in <top (required)>'
```

stopping at this point since i am not sure what issues are systemic wise - before i start bug hunting i have to ensure thats not just a general issue i am not aware of?

**Comment by michaelbaudino** [comment]
Crap, sorry about that 😕 

Could you please post the output of:
```shell
cd ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux && cat mounts && git status
```

**Comment by michaelbaudino** [comment]
Also, [this comment](https://github.com/docker/for-mac/issues/1532#issuecomment-293322906) suggests to share **both** `/private/var/folders` and `/var/folders` 😕 (I don't understand why)

**Comment by michaelbaudino** [comment]
And finally, can you confirm that `/var` is a symlink to `/private/var` ?

**Comment by michaelbaudino** [comment]
I just pushed a version that correctly checks shared directories even if they contain a symlink. That won't solve your issue but at least it should not warn false-positives anymore.

**Comment by EugenMayer** [comment]
@michaelbaudino what about the <<<EOS statement not support .. there are only supported from 2.3 upwards and we support 2.0+ .. would you join me on the point that we need to have the test running on the main platform, which would be Sierra with plain ruby, thus 2.0 ?

**Comment by michaelbaudino** [comment]
You're so right, it's fixed 👍

**Comment by ignatiusreza** [comment]
Hi guys! Sorry, was out of the grid for a while.. took a look into this, and it looks quite solid.. unfortunately I won't be able to help much here, since I'm using ubuntu and this PR is focusing on testing native_osx..

running this PR under my environment failed with 2 failure.. meaning that we should probably skip `native-osx_strategy_spec.rb` under non-osx environment..

**Comment by michaelbaudino** [comment]
I'll try to address @ignatiusreza issue tomorrow morning (not running OSX-only tests when the test suite runs on non-OSX systems).

@EugenMayer is there anything I can do to move this PR forward, from your point of view?

> 📚 Note to self: [FakeFS](https://github.com/fakefs/fakefs) looks like an interesting alternative to [RSpec::Bash](https://github.com/mdurban/rspec-bash).

**Comment by EugenMayer** [comment]
@michaelbaudino yes, could you just make my day 28 hours so I have more time? :) No @michaelbaudino  this stuff gets merged for sure, but having it in a branch / or for analysis makes most of sense for now. Other then that, you can merge it anytime.. but I like the pressure on me moving this PR forward... Since it's a huge effort and awesome work!

**Comment by michaelbaudino** [comment]
OK, all tests are now passing on my computer (Docker 17.06 on OSX 10.12.5). The expected synchronization times might need some tuning to pass on slower computers too.

OSX-specific specs are now skipped when not running the test suite on OSX (which should make `bundle exec rspec spec/integration` pass on @ignatiusreza computer 🐧).

Also, I can't configure Travis for this repository, I think only the owner can 😢

**Comment by EugenMayer** [comment]
@michaelbaudino just ran the tests and fixed some minor old ones i have written. Still running your tests, one failed on the first run:

```
 behaves like a synchronized directory
      synchronizes files deletions (FAILED - 1)
```

with

```
1) native_osx strategy start behaves like a synchronized directory synchronizes files deletions
     Failure/Error: expect(host_app_path).to be_in_sync_with(container_dir).in_container('docker_sync_specs-sync').within(options[:within])

       Expected `/app_sync` filetree in container `docker_sync_specs-sync` to match `/var/folders/b3/3z43880s2t9cjjqw3s38f2r40000gn/T/d20170706-88457-70fe3g/app_skeleton` filetree on host within 4 seconds.
       Diff:
       @@ -1,4 +1,3 @@
        a3ed74c55d40e42fbe0c7ab1581c0b3eb4c5fa18166f0d7c8ab1963c65c4bf59  ./Makefile
       -84e7ecc1e38f0079f25dd5583442ddb5943ed83178cbcdd82bacd3558d55be69  ./README.md
        90ba1e6bef8508ec10a4138f29de65298c9652a5f0917564c11575fbeb48b001  ./src/main.c

     Shared Example Group: "a synchronized directory" called from ./spec/integration/native-osx_strategy_spec.rb:43
     # ./spec/shared_examples/synchronization_shared_examples.rb:20:in `block (2 levels) in <top (required)>'
     # ./spec/integration/native-osx_strategy_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./spec/integration/native-osx_strategy_spec.rb:24:in `block (3 levels) in <top (required)>'
```

interestingly, running it the second time yielded no failures. Could it be that we are masking an issue by having some restovers that fix the run in the next runs?

Running the tests the third one, something different failed:

```
 behaves like a synchronized directory
      synchronizes on startup
      synchronizes files additions (FAILED - 1)
```

with

```
1) native_osx strategy start behaves like a synchronized directory synchronizes files additions
     Failure/Error: expect(host_app_path).to be_in_sync_with(container_dir).in_container('docker_sync_specs-sync').within(options[:within])

       Expected `/host_sync` filetree in container `docker_sync_specs-sync` to match `/var/folders/b3/3z43880s2t9cjjqw3s38f2r40000gn/T/d20170706-91137-13pa7o9/app_skeleton` filetree on host within 2 seconds.
       Diff:
       @@ -1,4 +1,5 @@
        a3ed74c55d40e42fbe0c7ab1581c0b3eb4c5fa18166f0d7c8ab1963c65c4bf59  ./Makefile
        84e7ecc1e38f0079f25dd5583442ddb5943ed83178cbcdd82bacd3558d55be69  ./README.md
       +be3eca3d78c39ffe52188a41184400a7763e39ed98e6198f474e35992df9b841  ./new_file.txt
        90ba1e6bef8508ec10a4138f29de65298c9652a5f0917564c11575fbeb48b001  ./src/main.c

     Shared Example Group: "a synchronized directory" called from ./spec/integration/native-osx_strategy_spec.rb:42
     # ./spec/shared_examples/synchronization_shared_examples.rb:10:in `block (2 levels) in <top (required)>'
     # ./spec/integration/native-osx_strategy_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./spec/integration/native-osx_strategy_spec.rb:24:in `block (3 levels) in <top (required)>'
```

Running it the forth time leaded to even more issues:

```
  behaves like a synchronized directory
      synchronizes files deletions
      synchronizes files changes (FAILED - 1)
      synchronizes on startup
      synchronizes files additions (FAILED - 2)
```

We need to get those tests a bit more reliable so we can trust them - do you have a smell were those issues come from?

Also, i get the "OS temporary folder" warning still, eventough its shared.

-----

Configuring travis - i will try to do so, never did that yet, but i guess that wont be to hard either :)

**Comment by michaelbaudino** [comment]
@EugenMayer Thanks for testing and giving feedback. Your inconsistency issue is clearly caused by the fact that your computer is synchronizing at the edge of the expected time: sometimes it's just fast enough, sometimes just a little too slow (which fails the test).

I just pushed a commit that changes synchronization expectation from `2.seconds` for `/host_sync` and `4.seconds` for `/app_sync` to `5.seconds` for `/host_sync` and `10.seconds` for `/app_sync`.

Let me know how it goes, but I'm pretty confident it will work 👍 (if not, you can also try to increase them locally and run the suite again)

**Comment by EugenMayer** [comment]
@michaelbaudino ok interesting. Used a pretty good hw ( laptop though ) - will try on it later.

On my desktop, the tests now work in a sequence - good stuff!

Travis is now configured, we still need a configuration for it to run our branches properly though.

**Comment by EugenMayer** [comment]
@michaelbaudino travis runs well now. I downgraded activesupport to 4.x latest to be able to use it with ruby 2.0.x - as 5.x is ruby 2.2+

the linux integration tests now run well under linux, also the other tests (project_settings seem to need some work though).

So eventhough we cannot run you integration tests under OSX automated with travis, we do so under linux ( smoke tests ) and i will run this under OSX before release as a policy.

For me, this Pr is good to go - @michaelbaudino if you feel like that, press the merge button, its all yours.

**Comment by EugenMayer** [comment]
great stuff! Thank you for this huge effort!

**Pull request merged**
