### PR TITLE
Migrate wiki content to Read The Docs

### LINKED ISSUE #355: [idea] Migrate docs to https://readthedocs.org/
The wiki becomes pretty painful already, including missing features like proper toc, deep links, stable links but also a proper navigation.

I would like to migrate them into https://readthedocs.org/

Does anybody want to help with this task - this would be great!

I want to change the structure a bit - we have 2 main topics:

a) Beginners / Starters / Common Case
b) Advanced

Into a) i want only deal with describing things you do on top of the default sync strategies. So no special selection of those here, not read advanced things like sync_args and so on. 
Just how to get on board, what you need to look at ( like sync_userid ), ho to create your compose files, how to name things.

b) describe all strategies, for each, the available configurations. Describe the global configuration, scaffolding, development/contribution, matter of autoupgrades and so on

### PR DESCRIPTION
**Pull request by unnawut**
Closes #355 

I basically moved the content over as is, and made styling modifications where Github markdown is not compatible with reStructuredText.

Then revamp the content structure by grouping similar content into the same pages and rename most of the pages so that they are common names that can usually be found in other documentations.

See the render of this pull request at: https://unnawut-docker-sync.readthedocs.io/en/readthedocs/

Once this PR is merged and hopefully, by default, Read The Docs would pick up the changes from master and render to https://docker-sync.readthedocs.io/en/latest/ almost immediately.

Once merged, I would recommend nuking the Wiki immediately to avoid confusion and double source of truth.

-----

For future references, these three links got easy-to-read content on what structure and styling is possible with Read The Docs:

- https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/structure.html
- http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
- http://docutils.sourceforge.net/docs/user/rst/quickref.html#directives

### CODE REVIEW

**Comment by EugenMayer** [comment]
Wow! Let me take some time to check and see how we can move this forward.
Thank you so much!

**Comment by EugenMayer** [comment]
Just had my first view on it. What shall i say? This is probably one of the biggest or at least most important contribution in a long time. This is really huge!

You used so many more markup tools to make the whole "important" "tip" "hint" things a lot more practical - and will avoid a lot more issues which always happened since people understandable overlooked them. 

The outline is _lovely_, really well crafted.

This docs are galaxies better then what we have right now, so i fully opt in to merge those right away.
Surely there will be little gliches, typos (as there always have been :) ) but we can fix them undergo. 

This docs will just help

**Comment by EugenMayer** [comment]
After this merge we might finally tackle https://github.com/EugenMayer/docker-sync/issues/39 and make this more practical - i am really looking forward to have it all on this level.

@unnawut if you want to join the club of contributors in here - i would anytime invite you to do so. Be it for the docs or code wise, obviously you have more then enough you could contribute and help with.

**Comment by unnawut** [comment]
Thank you so much for the offer. Although I think it's not the right time yet given my lack of knowledge for Ruby and operating systems and short commitments so far.

There's still a lot that can be done with structuring, styling, typos and content in general. Very happy to contribute more to the docs though.

**Comment by EugenMayer** [comment]
You are part of the family - welcome and thank you.

**Comment by EugenMayer** [comment]
Lets continue in https://github.com/EugenMayer/docker-sync/issues/355 for all the other bits and pieces

**Pull request merged**
