### PR TITLE
Make docker-sync consistently find docker-sync.yml from subfolders

### LINKED ISSUE #729: native_osx strategy does not run when running docker-sync from subfolder
### Error/Feature Requestion/Docs
```
➜ ls ../docker-sync.yml
../docker-sync.yml
➜ docker-sync start
          ok  Starting native_osx for sync community-sync
Traceback (most recent call last):
	14: from /Users/gostrolucky/.gem/ruby/2.6.0/bin//docker-sync:23:in `<main>'
	13: from /Users/gostrolucky/.gem/ruby/2.6.0/bin//docker-sync:23:in `load'
	12: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/bin/docker-sync:14:in `<top (required)>'
	11: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	10: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 9: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 8: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 7: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/tasks/sync/sync.thor:47:in `start'
	 6: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/tasks/sync/sync.thor:170:in `daemonize'
	 5: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_manager.rb:102:in `start_container'
	 4: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_manager.rb:102:in `each'
	 3: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_manager.rb:103:in `block in start_container'
	 2: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_process.rb:105:in `start_container'
	 1: from /Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_strategy/native_osx.rb:41:in `start_container'
/Users/gostrolucky/.gem/ruby/2.6.0/gems/docker-sync-0.5.14/lib/docker-sync/sync_strategy/native_osx.rb:41:in `realpath': No such file or directory @ realpath_rec - /Users/gostrolucky/PhpstormProjects/calida/community/community (Errno::ENOENT)
➜ cd ..
➜ docker-sync start
          ok  Starting native_osx for sync community-sync
          ok  community-sync container still running, restarting unison in container
unison: stopped
unison: started
     success  Sync container started
          ok  Starting native_osx for sync shop-sync
shop-sync
unix:///tmp/supervisor.sock no such file
     success  Sync container started
     success  Starting Docker-Sync in the background
```

### Docker Driver
d4m

### Sync strategy
default

### your docker-sync.yml
irrelevant

### OS
MacOS Catalina

### PR DESCRIPTION
**Pull request by ostrolucky**
Aim of this is to make all commands working even when docker-sync.yml is not in current dir, but in one of the children

Fixes #729

### CODE REVIEW

**Comment by EugenMayer** [comment]
Not going to merge this one before extensive testing - this has been tried several times and AFAIR we always failed with the docker-compose context and others - i would postpone this one. 

It is nice to have, but fairly hard to implement in the context we currently drive hin, way to many path related, root folder, log folder and more, risky with not enough gain, IMHO

**Comment by ostrolucky** [comment]
Alright, could you link me up to previous attempts please? So I can learn from past and check what I need to watch out for. I am not really sure what you meant with contexts etc.

**Comment by EugenMayer** [comment]
Cannot really remember / make up how to find them, i just remember in the backhead that this was problematic. Sorry of not being of better help here

**Comment by EugenMayer** [comment]
Could you please fix the tests failing for this PR so we can continue the review? Thank you for the effort

**Comment by ostrolucky** [comment]
On my to-do list. I might have a time for this in weekend

**Comment by ostrolucky** [comment]
Hmm while working on this, I've actually discovered option `project_root: config_path`, which does what I want. I think it would make more sense for it to be a default though. I've created #741 to discuss that.

**Pull request closed without merging**
