### PR TITLE
Property  Property documentation: Rework configuration reference

### PR DESCRIPTION
**Pull request by cweiske**

### CODE REVIEW

**Comment by cweiske** [comment]
https://docker-sync--746.org.readthedocs.build/en/746/getting-started/configuration.html#docker-sync-yml

**Comment by EugenMayer** [comment]
Thank you for reopening the PR .. we finally now have the builds for readthedocs.

I took the liberty ( sorry if too bold ) and reworked the configuration files in those terms

 - use a table for the possible values
 - rename General Options to Advanced options
 - Move Advanced options below sync options ( synce this is a advanced topic )
 - reorder sync options by importance and mark the mandatory ones with `*`
 - change some documentation, clarification and outdated things which i stubled upon

https://gist.github.com/EugenMayer/ae6ad65aa1a7cf4de60ac45b9d026b13

Could you just use this as your starting point to continue with your work. I used you latest version as my starting point and just worked on top of that. 

I hope you like the changes, but of course, feel free to go with any suggestion. 

Thank you for your effort!

**Comment by cweiske** [comment]
Please adjust the PR with your changes - I have no problems with that.

**Comment by cweiske** [comment]
I added your changes as new commit.

**Comment by cweiske** [comment]
Looks fine now.

**Comment by EugenMayer** [comment]
This is so much better then what we have live right now - you did a so much valuable job here, thank you so much!

**Pull request merged**
