### PR TITLE
Wait for Unison to start before tailing its log

### PR DESCRIPTION
**Pull request by michaelbaudino**
This PR fixes the error when unison does not start fast enough and that we try to `tail` on the log file that has not yet been created.

```
   Sync Log:  tail: can't open '/tmp/unison.log': No such file or directory
   Sync Log:  tail: no files
```

ℹ️ to easily reproduce, I run `docker-sync clean` before running `docker-sync start`

### CODE REVIEW

**Comment by EugenMayer** [comment]
We should also address this one https://github.com/EugenMayer/docker-sync/issues/357 but i guess, we have to split efforts, right?

**Comment by EugenMayer** [comment]
we might not just wait for the log to spawn, but rather check for a specific string which tells us something like "initial sync done"

**Comment by EugenMayer** [comment]
i solved #366 in the image but also added /tmp/unison.log to the image https://github.com/EugenMayer/docker-image-unison/commit/545bec3d4e47b4e2a991d21901d211f0dcecf0a2 this should make this obsolete and robust, would it?

The point with your wait is, that if the src folder is empty during the initial start, the log is never created and the watch is getting a timeout. Sure, its unpractical but can happen - the way adding it to the image deals with both.

What do you think?

**Comment by EugenMayer** [comment]
try

```
gem uninstall docker-sync 
gem install docker-sync --version 0.4.3-beta1
```

And tell me how you think it works without this patch in your env

**Comment by michaelbaudino** [comment]
Yup: https://github.com/EugenMayer/docker-image-unison/commit/545bec3d4e47b4e2a991d21901d211f0dcecf0a2 should fix it 👍 

But I think we still need to use `tail -F` rather than `tail -f` (because `-F` reloads the file if it is re-created by an external process). Here is an extract from `man tail`:

```
       -f, --follow[={name|descriptor}]
              output appended data as the file grows; -f, --follow, and --follow=descriptor are equivalent

       -F     same as --follow=name --retry

       --retry
              keep trying to open a file even when it is or becomes inaccessible; useful when following by name, i.e., with --follow=name
```

Do you want a PR for this ?

**Comment by EugenMayer** [comment]
That makes a lot of sense actually. 

No jus tcommit that one, no need to overcomplicate thinks.

Thank you for joining the fight - close this PR if you consider it irrelevant

**Comment by michaelbaudino** [comment]
Yup, I pushed  directly to `master` the `tail -F` thing and also a fix of the version string that was causing this error:

```
→ docker-sync start --foreground
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string 0.4.3-beta1 (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.3.pre.beta1/lib/docker-sync/upgrade_check.rb:32:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.3.pre.beta1/lib/docker-sync/upgrade_check.rb:32:in `should_run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.3.pre.beta1/lib/docker-sync/upgrade_check.rb:14:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.3.pre.beta1/tasks/sync/sync.thor:34:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.4.3.pre.beta1/bin/docker-sync:14:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'
```

Closing this PR 👍

**Pull request closed without merging**
